---
title: "bear_figure"
author: "Dennis Kim"
date: "2023-04-19"
output: html_document
---

# Objective 

Create a figure of the bear TSLV esimates from two different models 

## Document Preamble 
```{r preamble, include = FALSE}
# load libraries
library(knitr)
library(here)
library(amt)
library(ggplot2)
library(tidyverse)
library(broom)
library(cowplot)
library(car)
options(width = 150)

# set knitr options 
opts_chunk$set(fig.width = 6, fig.height = 5, comment = NA)
```

# Data preparation

Read in the ssf data 
```{r}
# read the ssf bear data
ssfdat <- read.csv(here::here("data", "ssfdat.bear.final.tslv.csv"))

# create log_sl and cos_ta columns
ssfdat <- ssfdat %>% mutate(log_sl_ = log(sl_),
                            cos_ta_ = cos(ta_),
                            t1_ = as.POSIXct(t1_, format = "%Y-%m-%d %H:%M:%S"),
                            t2_ = as.POSIXct(t2_, format = "%Y-%m-%d %H:%M:%S"))

ssfdat %>% summary()
```
```{r model fit}
# quadratic terms of tslv x berries 
tslv.model <- ssfdat %>% filter(t1_ > "2006-05-24 04:18:00.00") %>% amt::fit_issf(case_ ~ berries + tslv + I(tslv^2) + log_sl_+ cos_ta_ + strata(step_id_), model = TRUE)

summary(tslv.model)
```

## Variance Inflation Factor (VIF)

```{r vif}
# calculate the VIF for each predictor variable in the model 
vif_values <- vif(tslv.model$model)
vif_values

# create horizontal bar chart to display each VIF value 
#barplot(vif_values, main = "VIF Values", horiz = TRUE, col = "steelblue")
```


## RSS for movements - SSF model

prepare dataframe for calculating RSS. 
```{r nonlinear RSS}
# Make a new data.frame for s1 
s1 <- data.frame(
    tslv = seq(from = 0, to = 370, length.out = 100),
    berries = 1.5,
    sl_ = 1080,
    log_sl_ = log(1080),
    cos_ta_ = 0.001766
)

# data.frame for s2 
s2 <- data.frame(
    tslv =  182.5,
    berries = 1.5,
    sl_ = 1080,
    log_sl_ = log(1080),
    cos_ta_ = 0.001766
)

# calculate log-RSS with large-sample confidence intervals 
lr_m1 <- amt::log_rss(tslv.model, s1, s2)

# check the header of the data.frame
head(lr_m1)

# get the rugs for used and available locations 
ssfdat1_use <- ssfdat %>% filter(case_ == TRUE) %>% select(tslv) %>% mutate(tslv_x1 = tslv, 
                                                             log_rss = 1) %>% select(-tslv)

ssfdat1_avail <- ssfdat %>% filter(case_ == FALSE) %>% select(tslv) %>% mutate(tslv_x1 = tslv, 
                                                             log_rss = 1) %>% select(-tslv)

# plot usinig ggplot2
p1 <- ggplot(lr_m1$df, aes(x = tslv_x1, y = exp(log_rss))) +
  geom_line(size = 1) +
  geom_hline(yintercept = 0,
             linetype = "dashed",
             color = "gray30") +
  geom_rug(data= ssfdat1_use, sides= "b", color = "darkgreen")+
  geom_rug(data = ssfdat1_avail, sides = "t", color = "brown")+
  xlim(0, 380)+
  xlab("Time Since Last Visit (Days)") +
  ylab("RSS vs Mean TSLV") +
  theme_bw()+
  ggtitle("SSA with a quadratic term for TSLV")

p1

# save the plot
ggsave("logRSS_bear.png", p1, width = 6, height = 4, dpi = 700, bg = NA)
```

## Thompson et al. 2022 model 
```{r thompson}
p2 <- ggplot(data.frame(x = c(0, 365)), aes(x = x), size = 5)+
  stat_function(fun = dnorm, args = list(352.2, 14.5), size = 1)+
  xlab("Time Since All The Previously Visited Areas (Days)")+
  ylab("Relative Attractiveness")+
  theme_bw()+
  ggtitle("(b) Thompson et al. 2022")

p2
```
combine the plots together 
```{r together}
cmb_plot <-
  plot_grid(
    p1,
    p2,
    nrow = 2
  )

cmb_plot

# save the plot 
ggsave("Bear_figure.png", p1, width = 5, height = 3)
```

## Footer
```{r footer}
sessionInfo()
```
